apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
- path: secrets.yaml
- path: deploy_service.yaml
- target:
    kind: Deployment
    name: rewild-deployment
  path: deploy_patch.json